package main.java;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

public class GameForm extends javax.swing.JFrame {

    public GameForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonWeiterA = new javax.swing.JButton();
        buttonWeiterB = new javax.swing.JButton();
        buttonBremsenA = new javax.swing.JButton();
        buttonBremsenB = new javax.swing.JButton();
        buttonBeschlA = new javax.swing.JButton();
        buttonBeschlB = new javax.swing.JButton();
        labelSpeedA = new javax.swing.JLabel();
        labelSpeedB = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        progressFuelA = new javax.swing.JProgressBar();
        progressFuelB = new javax.swing.JProgressBar();
        labelPlayerA = new javax.swing.JLabel();
        labelPlayerB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        buttonWeiterA.setText("Weiter");
        buttonWeiterA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWeiterAActionPerformed(evt);
            }
        });

        buttonWeiterB.setText("Weiter");
        buttonWeiterB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWeiterBActionPerformed(evt);
            }
        });

        buttonBremsenA.setText("Bremsen");
        buttonBremsenA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBremsenAActionPerformed(evt);
            }
        });

        buttonBremsenB.setText("Bremsen");
        buttonBremsenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBremsenBActionPerformed(evt);
            }
        });

        buttonBeschlA.setText("Beschleunigen");
        buttonBeschlA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBeschlAActionPerformed(evt);
            }
        });

        buttonBeschlB.setText("Beschleunigen");
        buttonBeschlB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBeschlBActionPerformed(evt);
            }
        });

        labelSpeedA.setText("0");

        labelSpeedB.setText("0");

        jPanel1.setBackground(new java.awt.Color(255, 128, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 128, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        progressFuelA.setForeground(new java.awt.Color(255, 178, 102));
        progressFuelA.setValue(100);

        progressFuelB.setForeground(new java.awt.Color(102, 178, 255));
        progressFuelB.setValue(100);

        labelPlayerA.setText("Spieler A");

        labelPlayerB.setText("Spieler B");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonWeiterA)
                            .addComponent(buttonBremsenA)
                            .addComponent(buttonBeschlA)
                            .addComponent(labelSpeedA)
                            .addComponent(progressFuelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(189, 189, 189)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonWeiterB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonBremsenB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonBeschlB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelSpeedB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(progressFuelB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelPlayerA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPlayerB)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlayerA)
                    .addComponent(labelPlayerB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelSpeedB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressFuelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(458, 458, 458)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonBeschlA)
                            .addComponent(buttonBeschlB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonBremsenA)
                            .addComponent(buttonBremsenB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonWeiterA)
                            .addComponent(buttonWeiterB)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSpeedA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressFuelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonWeiterAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWeiterAActionPerformed
        this.weiter(this.labelSpeedA, this.progressFuelA, this.buttonWeiterA);
    }//GEN-LAST:event_buttonWeiterAActionPerformed

    private void buttonWeiterBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWeiterBActionPerformed
        this.weiter(this.labelSpeedB, this.progressFuelB, this.buttonWeiterB);
    }//GEN-LAST:event_buttonWeiterBActionPerformed

    private void buttonBremsenAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBremsenAActionPerformed
        this.decreaseSpeed(this.labelSpeedA, 10);
    }//GEN-LAST:event_buttonBremsenAActionPerformed

    private void buttonBremsenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBremsenBActionPerformed
        this.decreaseSpeed(this.labelSpeedB, 10);
    }//GEN-LAST:event_buttonBremsenBActionPerformed

    private void buttonBeschlAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBeschlAActionPerformed
        this.increaseSpeed(this.labelSpeedA, 10);
    }//GEN-LAST:event_buttonBeschlAActionPerformed

    private void buttonBeschlBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBeschlBActionPerformed
        this.increaseSpeed(this.labelSpeedB, 10);
    }//GEN-LAST:event_buttonBeschlBActionPerformed

    private void increaseSpeed(JLabel label, int amount) {
        int currentValue = Integer.parseInt(label.getText());
        int newValue = currentValue + amount;
        label.setText(String.valueOf(newValue));
    }

    private void decreaseSpeed(JLabel label, int amount) {
        int currentValue = Integer.parseInt(label.getText());
        int newValue = currentValue - amount;
        if (newValue < 0) {
            label.setText("0");
        } else {
            label.setText(String.valueOf(newValue));
        }
    }

    private void weiter(JLabel label, JProgressBar progressbar, JButton button) {
        int speed = Integer.parseInt(label.getText());
        int currentValue = progressbar.getValue();
        int newValue = currentValue - (int)Math.sqrt(speed);
        progressbar.setValue(newValue);

        if (progressbar.getValue() <= 0) {
            button.setEnabled(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBeschlA;
    private javax.swing.JButton buttonBeschlB;
    private javax.swing.JButton buttonBremsenA;
    private javax.swing.JButton buttonBremsenB;
    private javax.swing.JButton buttonWeiterA;
    private javax.swing.JButton buttonWeiterB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelPlayerA;
    private javax.swing.JLabel labelPlayerB;
    private javax.swing.JLabel labelSpeedA;
    private javax.swing.JLabel labelSpeedB;
    private javax.swing.JProgressBar progressFuelA;
    private javax.swing.JProgressBar progressFuelB;
    // End of variables declaration//GEN-END:variables
}
