package main.java;

import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

public class GameForm extends javax.swing.JFrame {
    boolean isReadyA = false;
    boolean isReadyB = false;

    public GameForm(String nameP1, String nameP2) {
        initComponents();
        
        // Wert zwischen 3000 und 5000 ermitteln (random)
        int trackLength = ThreadLocalRandom.current().nextInt(3000, 5001);
        
        this.labelPlayerA.setText(nameP1);
        this.labelPlayerB.setText(nameP2);
        this.labelTrackLengthA.setText(String.valueOf(trackLength));
        this.labelTrackLengthB.setText(String.valueOf(trackLength));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonWeiterA = new javax.swing.JButton();
        buttonWeiterB = new javax.swing.JButton();
        buttonBremsenA = new javax.swing.JButton();
        buttonBremsenB = new javax.swing.JButton();
        buttonBeschlA = new javax.swing.JButton();
        buttonBeschlB = new javax.swing.JButton();
        labelSpeedA = new javax.swing.JLabel();
        labelSpeedB = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        progressFuelA = new javax.swing.JProgressBar();
        progressFuelB = new javax.swing.JProgressBar();
        labelPlayerA = new javax.swing.JLabel();
        labelPlayerB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelTrackLengthA = new javax.swing.JLabel();
        labelTrackLengthB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        buttonWeiterA.setText("Weiter");
        buttonWeiterA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWeiterAActionPerformed(evt);
            }
        });

        buttonWeiterB.setText("Weiter");
        buttonWeiterB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWeiterBActionPerformed(evt);
            }
        });

        buttonBremsenA.setText("Bremsen");
        buttonBremsenA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBremsenAActionPerformed(evt);
            }
        });

        buttonBremsenB.setText("Bremsen");
        buttonBremsenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBremsenBActionPerformed(evt);
            }
        });

        buttonBeschlA.setText("Beschleunigen");
        buttonBeschlA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBeschlAActionPerformed(evt);
            }
        });

        buttonBeschlB.setText("Beschleunigen");
        buttonBeschlB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBeschlBActionPerformed(evt);
            }
        });

        labelSpeedA.setText("0");

        labelSpeedB.setText("0");

        jPanel1.setBackground(new java.awt.Color(255, 128, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 128, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        progressFuelA.setForeground(new java.awt.Color(255, 178, 102));
        progressFuelA.setValue(100);

        progressFuelB.setForeground(new java.awt.Color(102, 178, 255));
        progressFuelB.setValue(100);

        labelPlayerA.setText("Spieler A");

        labelPlayerB.setText("Spieler B");

        jLabel1.setText("km/h");

        jLabel2.setText("km/h");

        labelTrackLengthA.setText("0");

        labelTrackLengthB.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelPlayerA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPlayerB))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSpeedA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(progressFuelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonWeiterA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonBremsenA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonBeschlA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTrackLengthA))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTrackLengthB)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressFuelB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelSpeedB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buttonWeiterB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonBremsenB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonBeschlB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlayerA)
                    .addComponent(labelPlayerB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTrackLengthA)
                    .addComponent(labelTrackLengthB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(labelSpeedB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressFuelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 462, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonBeschlA)
                            .addComponent(buttonBeschlB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonBremsenA)
                            .addComponent(buttonBremsenB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonWeiterA)
                            .addComponent(buttonWeiterB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSpeedA)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressFuelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonWeiterAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWeiterAActionPerformed
        if (this.isReadyB == true) {
            this.weiter();
        } else {
            this.isReadyA = true;
        }
    }//GEN-LAST:event_buttonWeiterAActionPerformed

    private void buttonWeiterBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWeiterBActionPerformed
        if (this.isReadyA == true) {
            this.weiter();
        } else {
            this.isReadyB = true;
        }
    }//GEN-LAST:event_buttonWeiterBActionPerformed

    private void buttonBremsenAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBremsenAActionPerformed
        this.decreaseSpeed(this.labelSpeedA, 10);
    }//GEN-LAST:event_buttonBremsenAActionPerformed

    private void buttonBremsenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBremsenBActionPerformed
        this.decreaseSpeed(this.labelSpeedB, 10);
    }//GEN-LAST:event_buttonBremsenBActionPerformed

    private void buttonBeschlAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBeschlAActionPerformed
        this.increaseSpeed(this.labelSpeedA, 10);
    }//GEN-LAST:event_buttonBeschlAActionPerformed

    private void buttonBeschlBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBeschlBActionPerformed
        this.increaseSpeed(this.labelSpeedB, 10);
    }//GEN-LAST:event_buttonBeschlBActionPerformed

    private void increaseSpeed(JLabel label, int amount) {
        int currentValue = Integer.parseInt(label.getText());
        int newValue = currentValue + amount;
        label.setText(String.valueOf(newValue));
    }

    private void decreaseSpeed(JLabel label, int amount) {
        int currentValue = Integer.parseInt(label.getText());
        int newValue = currentValue - amount;
        if (newValue < 0) {
            label.setText("0");
        } else {
            label.setText(String.valueOf(newValue));
        }
    }
    
    private void weiter() {
        this.progressFuelA.setValue(this.calcFuel(this.progressFuelA, this.labelSpeedA));
        this.progressFuelB.setValue(this.calcFuel(this.progressFuelB, this.labelSpeedB));

        if (this.progressFuelA.getValue() <= 0) {
            this.buttonWeiterA.setEnabled(false);
            this.isReadyA = true;
        } else {
            int speed = Integer.parseInt(this.labelSpeedA.getText());
            int trackLength = Integer.parseInt(this.labelTrackLengthA.getText());
            this.labelTrackLengthA.setText(String.valueOf(trackLength - speed));
            this.isReadyA = false;
        }
        
        if (this.progressFuelB.getValue() <= 0) {
            this.buttonWeiterB.setEnabled(false);
            this.isReadyB = true;
        } else {
            int speed = Integer.parseInt(this.labelSpeedB.getText());
            int trackLength = Integer.parseInt(this.labelTrackLengthB.getText());
            this.labelTrackLengthB.setText(String.valueOf(trackLength - speed));
            this.isReadyB = false;
        }
        
        if (this.progressFuelA.getValue() == 0 && this.progressFuelB.getValue() == 0) {
            if (Integer.parseInt(this.labelTrackLengthA.getText()) < Integer.parseInt(this.labelTrackLengthB.getText())) {
                gameOver(this.labelPlayerA);
            } else {
                gameOver(this.labelPlayerB);
            }
        }
    }

    private int calcFuel(JProgressBar progressFuel, JLabel labelSpeed) {
        int speed = Integer.parseInt(labelSpeed.getText());
        int currentValue = progressFuel.getValue();
        return currentValue - (int)Math.sqrt(speed);
    }

    private void gameOver(JLabel player) {
        String playerName = player.getText();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOverForm(playerName).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBeschlA;
    private javax.swing.JButton buttonBeschlB;
    private javax.swing.JButton buttonBremsenA;
    private javax.swing.JButton buttonBremsenB;
    private javax.swing.JButton buttonWeiterA;
    private javax.swing.JButton buttonWeiterB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelPlayerA;
    private javax.swing.JLabel labelPlayerB;
    private javax.swing.JLabel labelSpeedA;
    private javax.swing.JLabel labelSpeedB;
    private javax.swing.JLabel labelTrackLengthA;
    private javax.swing.JLabel labelTrackLengthB;
    private javax.swing.JProgressBar progressFuelA;
    private javax.swing.JProgressBar progressFuelB;
    // End of variables declaration//GEN-END:variables
}
