package main.java;

public class GameOverForm extends javax.swing.JFrame {

    public GameOverForm(Player winner) {
        initComponents();
        this.labelWinner.setText("Der Gewinner ist " + winner.getName() + "!");
    }

    public GameOverForm() {
        initComponents();
        this.labelWinner.setText("Unentschieden!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelWinner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelWinner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWinner.setText("Placeholder");
        labelWinner.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 20, 50, 20));
        labelWinner.setPreferredSize(new java.awt.Dimension(400, 120));
        getContentPane().add(labelWinner, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelWinner;
    // End of variables declaration//GEN-END:variables
}
