package main.java;

import java.awt.Rectangle;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JLabel;

public class GameForm extends javax.swing.JFrame {
    Track trackP1;
    Track trackP2;
    Player p1;
    Player p2;
    Car carP1;
    Car carP2;

    public GameForm(Player p1, Player p2) {
        initComponents();
        Weather w = new Weather();
        this.p1 = p1;
        this.p2 = p2;

        // rand int erzeugen
        int rand = ThreadLocalRandom.current().nextInt(500, 1001);

        this.trackP1 = new Track(rand);
        this.trackP2 = new Track(rand);
        this.carP1 = new Car(w.getSpeedMax());
        this.carP2 = new Car(w.getSpeedMax());

        this.labelPlayerA.setText(this.p1.getName());
        this.labelPlayerB.setText(this.p2.getName());

        this.trackP1.setSpeedMax(w.getSpeedMax());
        this.trackP1.setMileageFactor(w.getMileageFactor());
        this.trackP2.setSpeedMax(w.getSpeedMax());
        this.trackP2.setMileageFactor(w.getMileageFactor());
        this.labelWeather.setText(w.getType());
        this.labelTrackLengthA.setText(String.valueOf(this.trackP1.getLength()));
        this.labelTrackLengthB.setText(String.valueOf(this.trackP2.getLength()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonWeiterA = new javax.swing.JButton();
        buttonWeiterB = new javax.swing.JButton();
        buttonBremsenA = new javax.swing.JButton();
        buttonBremsenB = new javax.swing.JButton();
        buttonBeschlA = new javax.swing.JButton();
        buttonBeschlB = new javax.swing.JButton();
        labelSpeedA = new javax.swing.JLabel();
        labelSpeedB = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelCarP1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelCarP2 = new javax.swing.JLabel();
        progressFuelA = new javax.swing.JProgressBar();
        progressFuelB = new javax.swing.JProgressBar();
        labelPlayerA = new javax.swing.JLabel();
        labelPlayerB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelTrackLengthA = new javax.swing.JLabel();
        labelTrackLengthB = new javax.swing.JLabel();
        labelWeather = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        buttonWeiterA.setText("Weiter");
        buttonWeiterA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWeiterAActionPerformed(evt);
            }
        });

        buttonWeiterB.setText("Weiter");
        buttonWeiterB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWeiterBActionPerformed(evt);
            }
        });

        buttonBremsenA.setText("Bremsen");
        buttonBremsenA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBremsenAActionPerformed(evt);
            }
        });

        buttonBremsenB.setText("Bremsen");
        buttonBremsenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBremsenBActionPerformed(evt);
            }
        });

        buttonBeschlA.setText("Beschleunigen");
        buttonBeschlA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBeschlAActionPerformed(evt);
            }
        });

        buttonBeschlB.setText("Beschleunigen");
        buttonBeschlB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBeschlBActionPerformed(evt);
            }
        });

        labelSpeedA.setText("0");

        labelSpeedB.setText("0");

        jPanel1.setBackground(new java.awt.Color(255, 128, 0));

        labelCarP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/miara.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCarP1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(578, Short.MAX_VALUE)
                .addComponent(labelCarP1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 128, 255));

        labelCarP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/resources/italigto.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCarP2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelCarP2)
                .addContainerGap())
        );

        progressFuelA.setForeground(new java.awt.Color(255, 178, 102));
        progressFuelA.setValue(100);

        progressFuelB.setForeground(new java.awt.Color(102, 178, 255));
        progressFuelB.setValue(100);

        labelPlayerA.setText("Spieler A");

        labelPlayerB.setText("Spieler B");

        jLabel1.setText("km/h");

        jLabel2.setText("km/h");

        labelTrackLengthA.setText("0");

        labelTrackLengthB.setText("0");

        labelWeather.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWeather.setText("Wetter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSpeedA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(progressFuelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(buttonWeiterA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonBremsenA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonBeschlA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelPlayerA))
                .addGap(189, 189, 189)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTrackLengthA))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTrackLengthB)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(labelWeather, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressFuelB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelSpeedB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(buttonWeiterB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonBremsenB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonBeschlB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelPlayerB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlayerA)
                    .addComponent(labelPlayerB)
                    .addComponent(labelWeather))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTrackLengthA)
                    .addComponent(labelTrackLengthB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(labelSpeedB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressFuelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 634, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonBeschlA)
                            .addComponent(buttonBeschlB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonBremsenA)
                            .addComponent(buttonBremsenB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonWeiterA)
                            .addComponent(buttonWeiterB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSpeedA)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressFuelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonWeiterAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWeiterAActionPerformed
        if (this.p2.getIsReady() == true) {
            this.weiter();
        } else {
            this.p1.setIsReady(true);
            this.buttonWeiterA.setEnabled(false);
        }
    }//GEN-LAST:event_buttonWeiterAActionPerformed

    private void buttonWeiterBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWeiterBActionPerformed
        if (this.p1.getIsReady() == true) {
            this.weiter();
        } else {
            this.p2.setIsReady(true);
            this.buttonWeiterB.setEnabled(false);
        }
    }//GEN-LAST:event_buttonWeiterBActionPerformed

    private void buttonBremsenAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBremsenAActionPerformed
        this.decreaseSpeed(this.carP1, 10, this.labelSpeedA);
    }//GEN-LAST:event_buttonBremsenAActionPerformed

    private void buttonBremsenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBremsenBActionPerformed
        this.decreaseSpeed(this.carP2, 10, this.labelSpeedB);
    }//GEN-LAST:event_buttonBremsenBActionPerformed

    private void buttonBeschlAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBeschlAActionPerformed
        this.increaseSpeed(this.carP1, 10, this.labelSpeedA);
    }//GEN-LAST:event_buttonBeschlAActionPerformed

    private void buttonBeschlBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBeschlBActionPerformed
        this.increaseSpeed(this.carP2, 10, this.labelSpeedB);
    }//GEN-LAST:event_buttonBeschlBActionPerformed

    /**
     * Erhöht die Geschwindigkeit eines Spielers um die Menge amount.
     */
    private void increaseSpeed(Car car, int amount, JLabel speedLabel) {
        car.increaseSpeed(amount);
        speedLabel.setText(String.valueOf(car.getSpeed()));
    }

    /**
     * Verringert die Geschwindigkeit eines Spielers um die Menge amount.
     */
    private void decreaseSpeed(Car car, int amount, JLabel speedLabel) {
        car.decreaseSpeed(amount);
        speedLabel.setText(String.valueOf(car.getSpeed()));
    }

    /**
     * Setzt das Spiel fort, wenn beide Spieler bereit sind (nach einem Klick auf
     * "Weiter" werden this.isReadyA und this.isReadyB auf true gesetzt).
     */
    private void weiter() {
        // Nach jeder Runde wird die Tankanzeige der Spieler verringert.
        this.carP1.setFuel(this.carP1.getFuel() - (int)Math.sqrt(this.carP1.getSpeed()));
        this.carP2.setFuel(this.carP2.getFuel() - (int)Math.sqrt(this.carP2.getSpeed()));

        this.progressFuelA.setValue(this.carP1.getFuel());
        this.progressFuelB.setValue(this.carP2.getFuel());

        // Falls ein Spieler keinen Tank mehr hat, wird der Weiter-Button disablet.
        // Andernfalls wird die zurückgelegte Strecke von der noch zu fahrenden Strecke subtrahiert
        // und der Button wird wieder enablet.
        if (this.carP1.getFuel() <= 0) {
            this.p1.setIsReady(true);
            this.buttonBeschlA.setEnabled(false);
            this.buttonBremsenA.setEnabled(false);
            this.buttonWeiterA.setEnabled(false);
        } else {
            int speed = this.carP1.getSpeed();
            int trackLength = this.trackP1.getLength();

            int remainingTrack = trackLength - speed;
            
            if(speed > 0) {
                Rectangle bounds = this.jPanel1.getBounds();
                int upperLeftBound = bounds.y;
                int percentageRemainingTrack = (int) (((float)remainingTrack / trackLength) * 100);
                int percentageToGo = 100 - percentageRemainingTrack;
                int moveForward = (int) (upperLeftBound * ((double)percentageToGo / 100));
                
                int y = this.labelCarP1.getY() - moveForward;
                this.labelCarP1.setLocation(this.labelCarP1.getX(), y);
            }
            
            this.trackP1.setLength(remainingTrack);
            
           
            this.labelTrackLengthA.setText(String.valueOf(this.trackP1.getLength()));
            this.p1.setIsReady(false);
            this.buttonWeiterA.setEnabled(true);
        }

        if (this.carP2.getFuel() <= 0) {
            this.p2.setIsReady(true);
            this.buttonBeschlB.setEnabled(false);
            this.buttonBremsenB.setEnabled(false);
            this.buttonWeiterB.setEnabled(false);
        } else {
            int speed = this.carP2.getSpeed();
            int trackLength = this.trackP2.getLength();
            final int remainingTrack = trackLength - speed;
            
            if(speed > 0)
            {
                Rectangle bounds = this.jPanel2.getBounds();
                int upperLeftBound = bounds.y;
                int percentageTrack = (int) (((float)remainingTrack / trackLength) * 100);
                int percentageToGo = 100 - percentageTrack;
                int moveForward = (int) (upperLeftBound * ((double)percentageToGo / 100));
                int y = this.labelCarP2.getY();
                int newY = y - moveForward;

                this.labelCarP2.setLocation(this.labelCarP2.getX(), newY);
            }
                        
            this.trackP2.setLength(remainingTrack);

            this.labelTrackLengthB.setText(String.valueOf(this.trackP2.getLength()));
            this.p2.setIsReady(false);
            this.buttonWeiterB.setEnabled(true);
        }

        if (this.trackP1.getLength() <= 0 && this.trackP2.getLength() <= 0) {
            this.gameOverDraw();
        } else if (this.trackP1.getLength() <= 0) {
            this.gameOver(this.p1);
        } else if (this.trackP2.getLength() <= 0) {
            this.gameOver(this.p2);
        }

        // Falls beide Spieler keinen Tank mehr haben, wird das Spiel beendet.
        // Der Spieler mit der am weitesten zurückgelegten Strecke gewinnt.
        if (this.carP1.getFuel() <= 0 && this.carP2.getFuel() <= 0) {
            if (this.trackP1.getLength() < this.trackP2.getLength()) {
                this.gameOver(this.p1);
            } else {
                this.gameOver(this.p2);
            }
        }
    }

    /**
     * Ruft die "Game Over" Form mit dem Namen des Gewinners auf.
     */
    private void gameOver(Player winner) {
        this.setEnabled(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOverForm(winner).setVisible(true);
            }
        });
    }

    /**
     * Ruft die "Game Over" Form auf, wenn es einen Gleichstand gibt.
     */
    private void gameOverDraw() {
        this.setEnabled(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOverForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBeschlA;
    private javax.swing.JButton buttonBeschlB;
    private javax.swing.JButton buttonBremsenA;
    private javax.swing.JButton buttonBremsenB;
    private javax.swing.JButton buttonWeiterA;
    private javax.swing.JButton buttonWeiterB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCarP1;
    private javax.swing.JLabel labelCarP2;
    private javax.swing.JLabel labelPlayerA;
    private javax.swing.JLabel labelPlayerB;
    private javax.swing.JLabel labelSpeedA;
    private javax.swing.JLabel labelSpeedB;
    private javax.swing.JLabel labelTrackLengthA;
    private javax.swing.JLabel labelTrackLengthB;
    private javax.swing.JLabel labelWeather;
    private javax.swing.JProgressBar progressFuelA;
    private javax.swing.JProgressBar progressFuelB;
    // End of variables declaration//GEN-END:variables
}
