package main.java;

public class LauncherForm extends javax.swing.JFrame {

    public LauncherForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonStart = new javax.swing.JButton();
        labelSpielerA = new javax.swing.JLabel();
        labelSpielerB = new javax.swing.JLabel();
        textfieldNameA = new javax.swing.JTextField();
        textfieldNameB = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonStart.setText("Start");
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });

        labelSpielerA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpielerA.setText("Spieler 1");

        labelSpielerB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSpielerB.setText("Spieler 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSpielerB)
                        .addGap(18, 18, 18)
                        .addComponent(textfieldNameB))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSpielerA)
                        .addGap(18, 18, 18)
                        .addComponent(textfieldNameA)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(buttonStart)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldNameA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpielerA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldNameB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSpielerB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(buttonStart)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
        String nameP1 = this.textfieldNameA.getText();
        String nameP2 = this.textfieldNameB.getText();

        this.setVisible(false);

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Player p1 = new Player(nameP1);
                Player p2 = new Player(nameP2);
                new GameForm(p1, p2).setVisible(true);
            }
        });
    }//GEN-LAST:event_buttonStartActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonStart;
    private javax.swing.JLabel labelSpielerA;
    private javax.swing.JLabel labelSpielerB;
    private javax.swing.JTextField textfieldNameA;
    private javax.swing.JTextField textfieldNameB;
    // End of variables declaration//GEN-END:variables
}
